### ISSUE TITLE
FoxGuard Roadmap

### ISSUE THREAD

**Issue by gravityfox** [FoxDenStudio/FoxGuard#20]
This is a roadmap of things that will be done, in a vague order.

- [ ] Controllers
- [ ] User/Self Service
- [ ] Rewrite link and unlink commands to actually be usable.
- [x] Optimizations for handlers (Hashmap caching)
- [ ] Import objects
- [x] SuperRegions???
- [ ] Block WhiteList/BlackList
- [ ] More Flags

More things can and will be added along the way.

**Comment by szmarczak** [comment]
I've been using FoxGuard for a while, and I love it! It's very simple to use, interactive and very helpful.

In my opinion these issues need some attention:
https://github.com/FoxDenStudio/FoxGuard-Sponge/issues/81
https://github.com/FoxDenStudio/FoxGuard-Sponge/issues/106
